version: "3.9"
services:
  node:
    image: smartcontract/chainlink:1.0.1
    network_mode: "host"
    command: local n
    stdin_open: true
    tty: true
    env_file: ./chainlink/local.env
    ports:
      - 6688:6688
    depends_on:
      database:
        condition: service_healthy
      adapter:
        condition: service_started
  database:
    image: postgres:14
    network_mode: "host"
    restart: always
    domainname: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: pg_isready --username postgres
      interval: 10s
      timeout: 5s
      retries: 5
  adapter:
    image: public.ecr.aws/chainlink/adapters/view-function-adapter:1.0.2
    network_mode: "host"
    env_file: .adapter.env
    domainname: viewfunctionadapter
    ports:
      - 8080:8080
